variables:
    TIMEZONE:
        default: America/Chicago
        value: America/Chicago
        description: the timezone the servers should come up in
        overrides: null
        required: true
        type: null
    DATADOG_KEY:
        default: null
        value: null
        description: "If you have a datadog key, enter it here and we will install the agent"
        overrides: null
        required: false
